AppBundle\Entity\Place:
    attributes:
        id:
            groups: ['place', 'address']
        name:
            groups: ['place', 'address']
        rdvDuration:
            groups: ['place', 'address']
        address:
            groups: ['place']
        weeks:
            groups: ['week']

AppBundle\Entity\Week:
    attributes:
        id:
            groups: ['week']
        year:
            groups: ['week']
        weekNumber:
            groups: ['week', 'place']

AppBundle\Entity\Address:
    attributes:
        id:
            groups: ['place', 'address']
        number:
            groups: ['place', 'address']
        path:
            groups: ['place', 'address']
        city:
            groups: ['place', 'address']
        zipcode:
            groups: ['place', 'address']
        country:
            groups: ['place', 'address']
        places:
            groups: ['address']

AppBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'auth-token']
        name:
            groups: ['user', 'auth-token']
        firstname:
            groups: ['user', 'auth-token']
        email:
            groups: ['user', 'auth-token']

AppBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']